### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by caioaamaral** [ixblue/ixblue_ins_stdbin_driver#11]
I'm trying to build ixblue_ins_driver, but seems that since #10 the package is broken (ros ci is failling). I'm receiving the following error:

```
error: ‘class ixblue_stdbin_decoder::StdBinDecoder’ has no member named ‘parseNextFrame’
                 while(parser.parseNextFrame())
```

**Comment by romainreignier** [comment]
Hi @caioaamaral 

Thank you for reporting the issue.

A [new feature](https://github.com/ixblue/ixblue_stdbin_decoder/pull/6) as recently been merged in the `std_bin_decoder` package, breaking the current API.
A new release in on its way to the [buildfarm](https://github.com/ros/rosdistro/pull/27321).
#10 allow to make use of this new API.
In the meantime, the CI that are using the released packaged are failing, which is normal. But the CI using the master branches directly are [OK](https://github.com/ixblue/ixblue_ins_stdbin_driver/actions/runs/361320112).

So you can either use the released version from `apt`.
Or if you prefer to build this driver from source, uninstall the `std_bin_decoder` package and use the latest version from [the repo](https://github.com/ixblue/ixblue_stdbin_decoder) directly. It can now be used directly in your ROS workspace as a regular package with [catkin_make_isolated](https://www.ros.org/reps/rep-0134.html) or [catkin tools](https://catkin-tools.readthedocs.io/en/latest/).

Sorry for the inconvenience.

**Comment by caioaamaral** [comment]
Thank you for your fast answer. 

I was using `ixblue_ins_stdbin_driver` as a vc package, but the `ixblue_stdbin_decoder` is being installed by rosdep as a system dependency, so indeed I do not have this new release as it is still waiting for the approve at buildfarm. I'll revert my local branch to the previous commit until the `ixblue_stdbin_decoder`'s new release is available.  

You may close this issue, thanks for the help.

**Comment by caioaamaral** [comment]
@romainreignier is there already an `ixblue_ins_stdbin_driver` kinetic release on the way with the current update (I mean #10)?

**Comment by romainreignier** [comment]
Not yet, I am waiting for https://github.com/ros/rosdistro/pull/27323 to be merged before triggering the release for Kinetic.
But in a few days it should be out. Then we will have to wait for the next Kinetic sync from OpenRobotics but it should happen before the end of the month I guess.

**Comment by romainreignier** [comment]
@caioaamaral The 0.1.5 version has been released on Kinetic: https://discourse.ros.org/t/new-packages-for-kinetic-kame-2020-11-24/17545

**Comment by caioaamaral** [comment]
@romainreignier Thanks for the update :smiley:
