### ISSUE TITLE
NavSatFix message: Longitude is in the wrong format

### ISSUE THREAD

**Issue by RGoulartns** [ixblue/ixblue_ins_stdbin_driver#12]
The longitude value in a NavSatFix message shouldn't be larger than 180. Source: http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/NavSatFix.html

Currently, the driver reports values from 0 to 360 (instead of -180 to 180)

**Comment by romainreignier** [comment]
Hi @RGoulartns 
Good catch!
Thank you for your report, a fix is on its way.
