### ISSUE TITLE
not producing /standard/imu when used with phins

### ISSUE THREAD

**Issue by JFMatch** [ixblue/ixblue_ins_stdbin_driver#16]
Hello, I am using this driver with a phins surface iii. I see that it is producing /standard/navsatfix and also /ix/ins but its not producing /standard/imu though it is creating the topic. 

Is there a dependency on a particular phins firmware?

Any other ideas on what to look for to trouble shoot?

Thanks!!

**Comment by JFMatch** [comment]
Updated the INS firmware and now it is working as expected.

**Comment by jiheddachraoui** [comment]
Hi @JFMatch , I'd like to know how you updated the firmware. I inherited a system installed by someone else, and it seems we're facing the same problem.

**Comment by romainreignier** [comment]
Hi @jiheddachraoui 
You should contact the support team to help you update tour firmware:
https://www.ixblue.com/contact/?form_id=support

**Comment by jiheddachraoui** [comment]
Hello @romainreignier , thank you for your response. 
Before proceeding with the firmware update, I want to double-check if there are any specific configurations or alternative solutions for this issue, as everything seems fine on the web interface.

**Comment by romainreignier** [comment]
Hello @jiheddachraoui 
To have the INS message published, you need [this condition](https://github.com/ixblue/ixblue_ins_stdbin_driver/blob/3b1212a12f981810a03128f9d8f89ae0b490045f/ixblue_ins_driver/src/ros_publisher.cpp#L168-L176) to be true.
If you don't have the topic published, it means that your system does not provide one of the required STDBIN blocks.
You might try change the code to skip a block or use another one but some information will be missing or not follow ROS convention.

**Comment by jiheddachraoui** [comment]
Thanks @romainreignier  for getting back to me quickly. I'll look into this matter more deeply.
Do you think the update is crucial and will directly fix this issue?
Just to confirm: my system (Atlans A7)  is initialized correctly, and I'm already receiving messages from all topics except for /standard/imu.
