### ISSUE TITLE
No output from echo /topic

### ISSUE THREAD

**Issue by Kupofty** [ixblue/ixblue_ins_stdbin_driver#18]
Hi ! 
I'm trying to do an experiment with the PHINS C7 COMPACT and i want a rosbag of the imu data.
So I did the 'roslaunch ixblue_ins_driver ixblue_ins_driver.launch' and I can see the topics list. But when I want to echo a topic there's no data on it.
Any idea what I could be doing wrong, did I forget to do something ?

Thanks ! =)

**Comment by romainreignier** [comment]
Hi @Kupofty 
Are you sure that the PHINS has an Output configured to output **IXBLUE STD BIN V3** on **UDP** with the IP of your computer and 8200 as port?
As shown on the screenshot of this page: https://wiki.ros.org/ixblue_ins_driver

You can check with netcat that UDP datagrams are sent to your computer with the following command which should print binary data:
```
nc -lu 8200
```

**Comment by Kupofty** [comment]
Thanks that fixed it (and some modification in the firewall), it was on TCP and not UDP !

**Comment by jiheddachraoui** [comment]
Hello @romainreignier, I configured the output on the web interface as instructed, and running 'nc -lu 8200' shows binary data. However, when I launch the node, I encounter the same issue with empty topics. Additionally, my web interface remains stuck in orange with a waiting status.

**Comment by romainreignier** [comment]
Hello @jiheddachraoui 
It is a good sign if you get binary data on port 8200 with netcat.
In the driver, there is a check ([HERE](https://github.com/ixblue/ixblue_ins_stdbin_driver/blob/3b1212a12f981810a03128f9d8f89ae0b490045f/ixblue_ins_driver/src/ros_publisher.cpp#L69-L77)) if the system is initialized. If not, the method is returned without publishing any message.
So first, make sure to get your system initialized (blue in web interface) .
