### ISSUE TITLE
Problem with linear acceleration values

### ISSUE THREAD

**Issue by Kupofty** [ixblue/ixblue_ins_stdbin_driver#19]
Hi ! 

I'm plotting Linear Acceleration value (ixblue_ins_driver -> standard -> imu -> linear_acceleration ) of the PHINS COMPACT C7 on plotJuggler and i saw that the z value wasn't 9.81 m/s² (on a flat surface), it was either 8m/s² or directly 10m/s² with a little shake.
The probleme is the same on the 3 axis. But the other topics work fine and the value transition are smooth (ex : pitch on the picture). 

Any idea what could be the problem and how to fix it ?

Thanks ! =)

![ixblue_problem_value](https://user-images.githubusercontent.com/69522980/120642132-ca0c8280-c474-11eb-82ba-c1c814bdbb68.png)

**Comment by romainreignier** [comment]
Hi @Kupofty 

These results are indeed surprising.
Until recently, we used to publish the compensated acceleration which was looking good.
You can try to set the `use_compensated_acceleration` to `true` to see if the values are better and report us back.
Note that the gravity is removed from theses values.

Also, please note that on the PHINS, the pitch sign is inverted as far as I know.

**Comment by Kupofty** [comment]
Works fine with the compensated acceleration and I will add gravity value on the axis depending on the roll and pitch values I guess.
 Thanks for the help, appreciate it !

**Comment by romainreignier** [comment]
Hi @Kupofty 
I am glad that you could use the compensated acceleration.
The issue you have encountered is a known issue of the PHINS C7 firmware. You should contact our support team to update the firmware of your device.

**Comment by Kupofty** [comment]
Hi @romainreignier 

I have been told we have the latest firmware on the PHINS, do you have move information on what version have the bug and which version have the correction for it ?

I filled the form on the ixblue website to contact the supports but is there a specific mail to contact for this kind of problem ?

**Comment by romainreignier** [comment]
Hi @Kupofty 

Do you have any news from the support team?

**Comment by Kupofty** [comment]
Hi @romainreignier !

No answer to my mail so far but I contacted my superior who managed to contact them directly, seems like there's a patch on the way.

**Comment by romainreignier** [comment]
Ok, great
